#!/usr/bin/env node
const fs = require('fs-extra')
const path = require('path')
const moment = require('moment')
const chalk = require('chalk')

const args = process.argv.slice(2)
const [title] = args || 'New Article'

const date = moment().format('YYYY-MM-DD')

const template = `---
title: '${title}'
date: '${date}'
draft: true
---

`

const dest = path.resolve(
  __dirname,
  `../content/articles/__drafts`,
  title,
  'index.md'
)

if (fs.existsSync(dest)) {
  console.error(chalk`{red Error} File ${dest} is already existed. \n`)
  process.exit(1)
}

fs.outputFileSync(dest, template, 'utf8')
console.log(chalk`{green Success} 🔖 Created file ${dest}. \n`)
process.exit(0)
